### ISSUE TITLE
Resolve `*` asterisk in paths

### ISSUE THREAD

**Issue by literat** [lmc-eu/twigx-bundle#4]
We should support the asterisk `*` in paths and recursively add all directories in a path.

Currently we must add each path as a new line in the configuration YAML to support more directories with components.

Where we can resolve this:
https://github.com/lmc-eu/twigx-bundle/blob/3cfc20b1bbae62cf3c0a9f6b925e49fb1c10fab4/src/DependencyInjection/CompilerPass/OverrideServiceCompilerPass.php#L34

Current
```yaml
spirit_web_twig:
    paths:
        - "%kernel.project_dir%/assets/design-system/twig-components"
        - "%kernel.project_dir%/src/Jobs/FrontBundle/Resources/views/Default/components"
    paths_alias: 'jobs-design-system'
```

Wanted
```yaml
spirit_web_twig:
    paths:
        - "%kernel.project_dir%/assets/design-system/twig-components"
        - "%kernel.project_dir%/src/Jobs/FrontBundle/Resources/views/*" // resolve every directory in this path
    paths_alias: 'jobs-design-system'
```
